import Layout from "@/components/Layout/Layout";
import Link from "next/link";
import LoginForm from '@/components/Auth/LoginForm';
import { redirect } from "next/navigation";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from 'next/headers';

export const metadata = {
    title: "Login",
    // description: "Generated by create next app",
};


export default async function Login() {

    const supabase = createServerComponentClient({ cookies });

    const { data: { user } } = await supabase.auth.getUser();

    if(user)
    {
        return redirect("/user/dashboard");
    }

    return (
        <>
            <Layout>
                <section className="blog-section">
                    <div className="container mx-auto p-4 mt-5">
                        <div className="text-center text-5xl font-bold mb-16 text-blue-500">Login </div>
                        <div className="text-sm breadcrumbs">
                            <ul>
                                <li>
                                    <Link href={"/"}>Home</Link>
                                </li>
                                <li>Login</li>
                            </ul>
                        </div>
                        <div className="flex justify-center">
                            <div className="w-full md:w-6/12 card shadow">
                                <div className="card-body">
                                    <div className="card-title text-2xl font-bold">Log in to your account</div>

                                    <LoginForm />

                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </Layout>
        </>
    );
}