import Logout from "@/components/Auth/Logout";
import Layout from "@/components/Layout/Layout";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from 'next/headers';
import Link from "next/link";
import { redirect } from "next/navigation";

export const metadata = {
    title: "Dashboard",
    // description: "Generated by create next app",
};


export default async function Dashboard() {

    const supabase = createServerComponentClient({ cookies });

    const { data: { user } } = await supabase.auth.getUser();

    if(! user)
    {
        return redirect("/login");
    }

    return (
        <>
            <Layout>
                <section className="blog-section">
                    <div className="container mx-auto p-4 mt-5">
                        <div className="text-center text-5xl font-bold mb-16 text-blue-500">Dashboard </div>
                        <div className="text-sm breadcrumbs">
                            <ul>
                                <li>
                                    <Link href={"/"}>Dashboard</Link>
                                </li>
                                <li>Logout</li>
                            </ul>
                        </div>
                        <div className="flex justify-center">
                            <div>
                                <div className="card-title text-2xl font-bold">Welcome to Dashboard</div>

                                <Logout />

                            </div>
                        </div>
                    </div>
                </section>
            </Layout>
        </>
    );
}