import Logout from "@/components/Auth/Logout";
import BackendMenu from "@/components/Layout/BackendMenu";
import Layout from "@/components/Layout/Layout";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from 'next/headers';
import Link from "next/link";
import { redirect } from "next/navigation";
import FeaturesForm from "../../components/FeaturesForm";

export const metadata = {
    title: "Features Create",
    // description: "Generated by create next app",
};


export default async function Edit({params}) {

    const supabase = createServerComponentClient({ cookies });

    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
        return redirect("/login");
    }

    const { data, error } = await supabase
    .from('features')
    .select('*')
    .eq('id', params.id);

  if(error) throw (error);

  let feature = data[0] ?? {};

    return (
        <>
            <Layout>
                <section className="blog-section">
                    <div className="container mx-auto p-4 mt-5">
                        <div className="text-center text-5xl font-bold mb-16 text-blue-500">Dashboard </div>
                        <div className="text-sm breadcrumbs mb-3">
                            <ul>
                                <li>
                                    <Link href={"/"}>Home</Link>
                                </li>
                                <li>Create</li>
                            </ul>
                        </div>
                        <div className="flex justify-center gap-3">
                            <div className="w-full md:w-3/12">
                                <div className="card shadow">
                                    <div className="card-body">
                                        <div className="card-title text-2xl font-bold">
                                            Dashboard
                                        </div>
                                        <BackendMenu />
                                    </div>
                                </div>
                            </div>

                            <div className="w-full md:w-9/12">
                                <div className="card shadow">
                                    <div className="card-body">
                                        <div className="flex justify-between item-center">
                                            <div className="card-title">Edit Features - {params.id}</div>
                                            <div className="">
                                                <Link href={"/admin/features/list"} className="btn btn-success">Cencel</Link>
                                            </div>
                                        </div>
                                        <FeaturesForm  feature={feature}/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </Layout>
        </>
    );
}