import Layout from "@/components/Layout/Layout";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from 'next/headers';
import Link from "next/link";
import { redirect } from "next/navigation";
import LayoutAuth from "@/components/Layout/LayoutAuth";
import WorkTable from "../components/WorkTable";

export const metadata = {
    title: "How It Works",
    // description: "Generated by create next app",
};


export default async function List() {

    const supabase = createServerComponentClient({ cookies });

    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
        return redirect("/login");
    }

    // const { data, error } = await supabase
    //     .from('features')
    //     .select('*')
    //     .order('id', { ascending: false });

    // if (error) throw (error);

    // let features = data;

    return (
        <>
            <Layout>
                <section className="blog-section">
                    <div className="container mx-auto p-4 mt-5">
                        <div className="flex justify-center gap-3">

                            <LayoutAuth>

                                <div className="flex justify-between item-center">
                                    <div className="card-title">How It Works</div>
                                    <div className="">
                                        <Link href={"/admin/how-it-works/create"} className="btn btn-primary">Add New</Link>
                                    </div>
                                </div>
                                <div className="overflow-x-auto">
                                    <WorkTable />
                                </div>
                            </LayoutAuth>
                        </div>
                    </div>
                </section>
            </Layout>
        </>
    );
}