import RegisterForm from "@/components/Auth/RegisterForm";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from 'next/headers';
import Link from "next/link";
import { redirect } from "next/navigation";
// import Link from "next/link";


export const metadata = {
    title: "Register",
    // description: "Generated by create next app",
};


export default async function Register() {

    const supabase = createServerComponentClient({ cookies });

    const { data: { user } } = await supabase.auth.getUser();

    if(user)
    {
        return redirect("/user/dashboard");
    }

    return (
        <>
            <section className="blog-section">
                <div className="container mx-auto p-4 mt-5">
                    <div className="text-sm breadcrumbs">
                        <ul>
                            <li>
                                <Link href={"/"}>Home</Link>
                            </li>
                            <li>Register</li>
                        </ul>
                    </div>
                    <div className="flex justify-center">
                        <div className="w-full md:w-6/12 card shadow">
                            <div className="card-body">
                                <div className="card-title text-2xl font-bold">Create your account</div>

                                <RegisterForm />
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    );
}